import React from 'react'

import articleStyles from '../styles/article.module.scss'

const Article = () => {
  return (
    <div>
      <div className={articleStyles.title}>
        <h1>
          What not to do in this COVID pandemic?
        </h1>
      </div>

      <div className={articleStyles.metaData}>
     
      </div>

      <div>
        <p>
        Each page generated by VuePress has its own pre-rendered static HTML, providing great loading performance and is SEO-friendly. Yet, once the page is loaded, Vue takes over the static content and turns it into a full Single-Page Application (SPA). Extra pages are fetched on demand as the user navigates around the site.
        </p>
      </div>
    </div>
  )
}

export default Article